### ISSUE TITLE
[Expected Bug] Error when using 32bit python docker image

### ISSUE THREAD

**Issue by lutfifadlan** [acheong08/ChatGPT#214]
**Describe the bug**
I'm using Docker and when running `docker-compose up --build`, `pip3 install -r requirements.txt` is producing `OSError: /usr/local/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory`. This is solved by simply use 64bit python docker image (e.g. amd64/python:3.11.1-bullseye)

**To Reproduce**
- `Dockerfile`:
```
FROM python:3.11.1-bullseye
ADD . /code
WORKDIR /code
RUN pip3 install -r requirements.txt
EXPOSE 8000
CMD python3 app.py
```
- `docker-compose.yml`:
```
services:
    web:
        build: .
        ports:
            - "8000:8000"
        stop_signal: SIGINT
        volumes:
            - .:/code
```
- Run `docker-compose up --build`

**Expected behavior**
It should successfully run `docker-compose up --build`

**How to solve**
Update `Dockerfile` to use `amd64/python:3.11.1-bullseye` instead
```
FROM python:3.11.1-bullseye
ADD . /code
WORKDIR /code
RUN pip3 install -r requirements.txt
EXPOSE 8000
CMD python3 app.py
```

**Recommendation**
- Add documentation about docker installation too
